
obj-y += dma_fence_test_kernel.o

# how to compile user bin tool:
#/home/ysh/code/toolchain/gcc-linaro-7.5.0-2019.12-rc1-x86_64_aarch64-linux-gnu/bin/aarch64-linux-gnu-gcc dma_fence_test_user.c -lpthread
#cp a.out ~/code/qemu/rootfs_busybox/usr/bin/dma_demo.bin
